apiVersion: v1
kind: ConfigMap
metadata:
  name: dumpster-cm
data:
  one: two
  key: value
---
apiVersion: v1
kind: Pod
metadata:
  name: dumpster-cm-volume
  labels:
    app: dumpster-cm-volume
    workshop: "true"
spec:
  containers:
  - name: dumpster-container
    image: gutek/dumpster:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: cm-volume
      mountPath: /var/data
  volumes:
  - name: cm-volume
    configMap:
      name: dumpster-cm