apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dumpster-live-dep
  labels:
    workshop: "true"
    app: dumpster-01
spec:
  replicas: 3
  selector:
    matchLabels:
      workshop: "true"
      app: dumpster-01
  template:
    metadata:
      name: dumpster-live-pod
      labels:
        workshop: "true"
        app: dumpster-01
    spec:
      containers:
      - name: dumpster-live-pod-container
        image: gutek/dumpster:v1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /test
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dumpster-live-svc
  labels:
    workshop: "true"
    app: dumpster-01
spec:
  type: NodePort
  selector:
    app: dumpster-01
    workshop: "true"
  ports:
  - name: http
    port: 80
    targetPort: 8080
