apiVersion: v1
kind: Service
metadata:
  name:  dumpster-svc
  labels:
    workshop: "true"
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080
