apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
data:
  DB_PASSWORD: cDZbUGVXeU5e0ZW
  REDIS_PASSWORD: AAZbUGVXeU5e0ZB
---
apiVersion: v1
kind: Pod
metadata:
  name: dumpster-secret-volume
  labels:
    app: dumpster-secret-volume
    workshop: "true"
spec:
  containers:
  - name: dumpster-container
    image: gutek/dumpster:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: secret-volume
      mountPath: /var/data
  volumes:
  - name: secret-volume
    secret:
      name: env-secrets