apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dumpster-revert-dep
  labels:
    workshop: "true"
    app: dumpster-revert
spec:
  replicas: 1
  selector:
    matchLabels:
      workshop: "true"
      app: dumpster-revert
  template:
    metadata:
      name: dumpster-revert-pod
      labels:
        workshop: "true"
        app: dumpster-revert
    spec:
      containers:
      - name: dumpster-revert-pod-container
        image: gutek/dumpser:v8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dumpster-revert-svc
  labels:
    workshop: "true"
    app: dumpster-revert
spec:
  type: NodePort
  selector:
    app: dumpster-revert
    workshop: "true"
  ports:
  - name: http
    port: 80
    targetPort: 8080