kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: simple-pv-claim
  labels:
    wokrshop: "true"
spec:
  storageClassName: simple-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi