apiVersion: batch/v1
kind: Job
metadata:
  name: dumpster-job
spec:
  template:
    metadata:
      labels:
          workshop: "true"
          app: dumpster-simple-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: dumpser-simple-job-container
          image: gutek/dumpster-job:v1