apiVersion: v1
kind: Service
metadata:
  name:  dumpster
  labels:
    workshop: "true"
spec:
  type: ClusterIP
  selector:
    app: dumpster
  ports:
  - name: http
    port: 80
    targetPort: 8080
