apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dumpster-dep
  labels:
    workshop: "true"
    app: dumpster-01
spec:
  replicas: 3
  selector:
    matchLabels:
      workshop: "true"
      app: dumpster-01
  template:
    metadata:
      name: dumpster-pod
      labels:
        workshop: "true"
        app: dumpster-01
    spec:
      containers:
      - name: dumpster-pod-container
        image: gutek/dumpster:v1
#         resources:
#           requests:
#           limits:
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dumpster-svc
  labels:
    workshop: "true"
    app: dumpster-01
spec:
  type: NodePort
  selector:
    app: dumpster-01
    workshop: "true"
  ports:
  - name: http
    port: 80
    targetPort: 8080
