apiVersion: v1
kind: Pod
metadata:
  name: dumpster-multi-volume
  labels:
    app: dumpster-multi-volume
    workshop: "true"
spec:
  containers:
  - name: dumpster-container
    image: gutek/dumpster:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: empty-volume
      mountPath: /var/data
  - name: generator-container
    image: busybox
    volumeMounts:
    - name: empty-volume
      mountPath: /local/data
    args:
      - /bin/sh
      - -c
      - while true; do echo Hello > "/local/data/$(date)"; sleep 60; done
  volumes:
  - name: empty-volume
    emptyDir: {}