apiVersion: v1
kind: Pod
metadata:
  name: dumpster-pod
  labels:
    workshop: "true"
    app: api
spec:
  containers:
  - name: dumpster-pod-container
    image: gutek/dumpster:v1
    ports:
    - containerPort: 8080
    env:
      - name: channel
        value: stable
      - name: month
        value: december
---
apiVersion: v1
kind: Service
metadata:
  name: pod-env
  labels:
    workshop: "true"
    app: dumpster
spec:
  type: NodePort
  selector:
    app: api
    workshop: "true"
  ports:
  - name: http
    port: 80
    targetPort: 8080
