apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumpster-deployment
  labels:
    app: dumpster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dumpster
  template:
    metadata:
      labels:
        app: dumpster
    spec:
      containers:
      - name: dumpster
        image: dumpster:v1
        ports:
        - containerPort: 80