apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dumpster-hpa
  labels:
    workshop: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dumpster-dep
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90