apiVersion: v1
kind: Pod
metadata:
  name: dumpster-env-pod
  labels:
    workshop: "true"
    app: api
spec:
  containers:
  - name: dumpster-env-pod-container
    image: gutek/dumpster:v1
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pod-cm-env
  labels:
    workshop: "true"
    app: dumpster
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080
